// Generated by tools/palettes.py -- edit that, not this.

export type Scheme = 'light' | 'dark';

export interface Swatch {
  sidebar: string;
  app: string;
  surface: string;
  accent: string;
  text: string;
  secondary: string;
}

export interface PaletteInfo {
  id: string;
  label: string;
  scheme: Scheme;
  description: string;
  /** What Settings draws for it, before it is applied. */
  swatch: Swatch;
}

export const PALETTES: PaletteInfo[] = [
  {
    id: 'code-dark',
    label: 'Code Dark',
    scheme: 'dark',
    description: "The editor's modern dark: neutral greys, one blue",
    swatch: {
      sidebar: '#181818',
      app: '#181818',
      surface: '#1f1f1f',
      accent: '#0078d4',
      text: '#cccccc',
      secondary: '#4ec9b0',
    },
  },
  {
    id: 'midnight',
    label: 'Midnight',
    scheme: 'dark',
    description: 'Deep indigo, soft blue and violet',
    swatch: {
      sidebar: '#16161e',
      app: '#16161e',
      surface: '#1a1b26',
      accent: '#7aa2f7',
      text: '#c0caf5',
      secondary: '#bb9af7',
    },
  },
  {
    id: 'arctic',
    label: 'Arctic',
    scheme: 'dark',
    description: 'Polar night greys and frost blues',
    swatch: {
      sidebar: '#2b303b',
      app: '#242933',
      surface: '#2e3440',
      accent: '#88c0d0',
      text: '#eceff4',
      secondary: '#c3a3be',
    },
  },
  {
    id: 'ember',
    label: 'Ember',
    scheme: 'dark',
    description: 'Warm charcoal, amber and orange',
    swatch: {
      sidebar: '#1d2021',
      app: '#1d2021',
      surface: '#282828',
      accent: '#fe8019',
      text: '#ebdbb2',
      secondary: '#8ec07c',
    },
  },
  {
    id: 'contrast-dark',
    label: 'High Contrast',
    scheme: 'dark',
    description: 'Black, white and hard edges, for legibility first',
    swatch: {
      sidebar: '#000000',
      app: '#000000',
      surface: '#000000',
      accent: '#6fc3df',
      text: '#ffffff',
      secondary: '#f38518',
    },
  },
  {
    id: 'code-light',
    label: 'Code Light',
    scheme: 'light',
    description: "The editor's modern light: white, grey and a deep blue",
    swatch: {
      sidebar: '#f8f8f8',
      app: '#f8f8f8',
      surface: '#ffffff',
      accent: '#005fb8',
      text: '#3b3b3b',
      secondary: '#267f99',
    },
  },
  {
    id: 'solar',
    label: 'Solar',
    scheme: 'light',
    description: 'Warm cream with the classic blues and cyans',
    swatch: {
      sidebar: '#eee8d5',
      app: '#eee8d5',
      surface: '#fdf6e3',
      accent: '#1c6aa5',
      text: '#073642',
      secondary: '#1d766f',
    },
  },
  {
    id: 'linen',
    label: 'Linen',
    scheme: 'light',
    description: 'Paper-warm neutrals and terracotta',
    swatch: {
      sidebar: '#efe8dc',
      app: '#f4efe6',
      surface: '#fbf8f2',
      accent: '#a3481f',
      text: '#2b2620',
      secondary: '#35695c',
    },
  },
  {
    id: 'contrast-light',
    label: 'High Contrast Light',
    scheme: 'light',
    description: 'White, black and hard edges, for legibility first',
    swatch: {
      sidebar: '#ffffff',
      app: '#ffffff',
      surface: '#ffffff',
      accent: '#0f4a85',
      text: '#000000',
      secondary: '#b5200d',
    },
  },
];

/** Each layout's own colours, drawn for "Layout colours" (tokens.css and variants.css). */
export const LAYOUT_SWATCHES: Record<string, Record<Scheme, Swatch>> = {
  studio: {
    dark: {
      sidebar: '#0b0f17',
      app: '#070a0f',
      surface: '#101621',
      accent: '#8174ff',
      text: '#f3f6fb',
      secondary: '#45d6d0',
    },
    light: {
      sidebar: '#eef1f5',
      app: '#f5f7fa',
      surface: '#ffffff',
      accent: '#6557f0',
      text: '#172033',
      secondary: '#16a8a3',
    },
  },
  relay: {
    dark: {
      sidebar: '#181818',
      app: '#181818',
      surface: '#1f1f1f',
      accent: '#4daafc',
      text: '#cccccc',
      secondary: '#4ec9b0',
    },
    light: {
      sidebar: '#f8f8f8',
      app: '#f8f8f8',
      surface: '#ffffff',
      accent: '#005fb8',
      text: '#3b3b3b',
      secondary: '#267f99',
    },
  },
  workshop: {
    dark: {
      sidebar: '#2b303b',
      app: '#242933',
      surface: '#2e3440',
      accent: '#88c0d0',
      text: '#eceff4',
      secondary: '#c3a3be',
    },
    light: {
      sidebar: '#f8f8f8',
      app: '#f8f8f8',
      surface: '#ffffff',
      accent: '#005fb8',
      text: '#3b3b3b',
      secondary: '#267f99',
    },
  },
  chronicle: {
    dark: {
      sidebar: '#1d2021',
      app: '#1d2021',
      surface: '#282828',
      accent: '#fe8019',
      text: '#ebdbb2',
      secondary: '#8ec07c',
    },
    light: {
      sidebar: '#efe8dc',
      app: '#f4efe6',
      surface: '#fbf8f2',
      accent: '#a3481f',
      text: '#2b2620',
      secondary: '#35695c',
    },
  },
  pulse: {
    dark: {
      sidebar: '#16161e',
      app: '#16161e',
      surface: '#1a1b26',
      accent: '#7aa2f7',
      text: '#c0caf5',
      secondary: '#bb9af7',
    },
    light: {
      sidebar: '#eee8d5',
      app: '#eee8d5',
      surface: '#fdf6e3',
      accent: '#1c6aa5',
      text: '#073642',
      secondary: '#1d766f',
    },
  },
  map: {
    dark: {
      sidebar: '#1d2021',
      app: '#1d2021',
      surface: '#282828',
      accent: '#fe8019',
      text: '#ebdbb2',
      secondary: '#8ec07c',
    },
    light: {
      sidebar: '#eee8d5',
      app: '#eee8d5',
      surface: '#fdf6e3',
      accent: '#1c6aa5',
      text: '#073642',
      secondary: '#1d766f',
    },
  },
  deck: {
    dark: {
      sidebar: '#000000',
      app: '#000000',
      surface: '#000000',
      accent: '#6fc3df',
      text: '#ffffff',
      secondary: '#f38518',
    },
    light: {
      sidebar: '#ffffff',
      app: '#ffffff',
      surface: '#ffffff',
      accent: '#0f4a85',
      text: '#000000',
      secondary: '#b5200d',
    },
  },
  instrument: {
    dark: {
      sidebar: '#0d0d0d',
      app: '#0a0a0a',
      surface: '#111111',
      accent: '#ededed',
      text: '#ededed',
      secondary: '#d4d4d4',
    },
    light: {
      sidebar: '#f4f4f4',
      app: '#fafafa',
      surface: '#ffffff',
      accent: '#0a0a0a',
      text: '#0a0a0a',
      secondary: '#404040',
    },
  },
  paper: {
    dark: {
      sidebar: '#1c1a17',
      app: '#171614',
      surface: '#1f1d1a',
      accent: '#e8804f',
      text: '#ede8de',
      secondary: '#86b8a2',
    },
    light: {
      sidebar: '#efece5',
      app: '#f6f4ef',
      surface: '#fbfaf7',
      accent: '#c2410c',
      text: '#1f1c18',
      secondary: '#3f6b5a',
    },
  },
  islands: {
    dark: {
      sidebar: '#15181d',
      app: '#0b0d10',
      surface: '#15181d',
      accent: '#5b7cff',
      text: '#e8ebf0',
      secondary: '#2dd4bf',
    },
    light: {
      sidebar: '#ffffff',
      app: '#e8ebf0',
      surface: '#ffffff',
      accent: '#2f5bff',
      text: '#111827',
      secondary: '#0ea5a4',
    },
  },
  mission: {
    dark: {
      sidebar: '#121417',
      app: '#0e1012',
      surface: '#16191c',
      accent: '#b8f36b',
      text: '#e6e9ec',
      secondary: '#5ad1e6',
    },
    light: {
      sidebar: '#ebece8',
      app: '#f3f4f1',
      surface: '#ffffff',
      accent: '#4d7c0f',
      text: '#15181b',
      secondary: '#0e7490',
    },
  },
  focus: {
    dark: {
      sidebar: '#0b0b0d',
      app: '#050506',
      surface: '#0f0f12',
      accent: '#a78bfa',
      text: '#f2f2f4',
      secondary: '#67e8f9',
    },
    light: {
      sidebar: '#f1f1f3',
      app: '#f7f7f8',
      surface: '#ffffff',
      accent: '#7c3aed',
      text: '#121216',
      secondary: '#0891b2',
    },
  },
};
