// Generated by tools/palettes.py -- edit that, not this.

export type Scheme = 'light' | 'dark';

export interface Swatch {
  sidebar: string;
  app: string;
  surface: string;
  accent: string;
  text: string;
  secondary: string;
}

export interface PaletteInfo {
  id: string;
  label: string;
  scheme: Scheme;
  description: string;
  /** What Settings draws for it, before it is applied. */
  swatch: Swatch;
}

export const PALETTES: PaletteInfo[] = [
  { id: 'code-dark', label: 'Code Dark', scheme: 'dark', description: "The editor's modern dark: neutral greys, one blue", swatch: { sidebar: '#181818', app: '#181818', surface: '#1f1f1f', accent: '#0078d4', text: '#cccccc', secondary: '#4ec9b0' } },
  { id: 'midnight', label: 'Midnight', scheme: 'dark', description: 'Deep indigo, soft blue and violet', swatch: { sidebar: '#16161e', app: '#16161e', surface: '#1a1b26', accent: '#7aa2f7', text: '#c0caf5', secondary: '#bb9af7' } },
  { id: 'arctic', label: 'Arctic', scheme: 'dark', description: 'Polar night greys and frost blues', swatch: { sidebar: '#2b303b', app: '#242933', surface: '#2e3440', accent: '#88c0d0', text: '#eceff4', secondary: '#c3a3be' } },
  { id: 'ember', label: 'Ember', scheme: 'dark', description: 'Warm charcoal, amber and orange', swatch: { sidebar: '#1d2021', app: '#1d2021', surface: '#282828', accent: '#fe8019', text: '#ebdbb2', secondary: '#8ec07c' } },
  { id: 'contrast-dark', label: 'High Contrast', scheme: 'dark', description: 'Black, white and hard edges, for legibility first', swatch: { sidebar: '#000000', app: '#000000', surface: '#000000', accent: '#6fc3df', text: '#ffffff', secondary: '#f38518' } },
  { id: 'code-light', label: 'Code Light', scheme: 'light', description: "The editor's modern light: white, grey and a deep blue", swatch: { sidebar: '#f8f8f8', app: '#f8f8f8', surface: '#ffffff', accent: '#005fb8', text: '#3b3b3b', secondary: '#267f99' } },
  { id: 'solar', label: 'Solar', scheme: 'light', description: 'Warm cream with the classic blues and cyans', swatch: { sidebar: '#eee8d5', app: '#eee8d5', surface: '#fdf6e3', accent: '#1c6aa5', text: '#073642', secondary: '#1d766f' } },
  { id: 'linen', label: 'Linen', scheme: 'light', description: 'Paper-warm neutrals and terracotta', swatch: { sidebar: '#efe8dc', app: '#f4efe6', surface: '#fbf8f2', accent: '#a3481f', text: '#2b2620', secondary: '#35695c' } },
  { id: 'contrast-light', label: 'High Contrast Light', scheme: 'light', description: 'White, black and hard edges, for legibility first', swatch: { sidebar: '#ffffff', app: '#ffffff', surface: '#ffffff', accent: '#0f4a85', text: '#000000', secondary: '#b5200d' } },
];

/** Focus colours, drawn for the default palette choice. */
export const LAYOUT_SWATCHES: Record<string, Record<Scheme, Swatch>> = {
  focus: { dark: { sidebar: '#0b0b0d', app: '#050506', surface: '#0f0f12', accent: '#a78bfa', text: '#f2f2f4', secondary: '#67e8f9' }, light: { sidebar: '#f1f1f3', app: '#f7f7f8', surface: '#ffffff', accent: '#7c3aed', text: '#121216', secondary: '#0891b2' } },
};
