[package]
name = "pwr-repo"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
chrono.workspace = true
ignore.workspace = true
rusqlite.workspace = true
pwr-domain = { path = "../pwr-domain" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tempfile.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true
